
MEAN_NAN: False # Строки со значением Nan заменяются стредними значениями столбца
DROP_NAN: True # Строки со значением Nan удаляются


ROLLING_MEAN: False
EXP_SMOOTH: False
DOUBLE_EXP_SMOOTH: False
ROLLING_MEAN_WINDOW: 32

ROLLING_MEAN_LOSS: 32
COUNT_ANOMALY: 100
ANOMALY_TRESHOLD: 0.99
COUNT_TOP: 3

AUTO_DROP_LIST: False
DROP_LIST: [] #удаление датчиков из отчета CSV
PLOT_FEATURES: ['Sochi2.GT.AM.20MKA10CT005G','Sochi2.GT.AM.20MKA10CT010G', 'Sochi2.GT.AM.20MKA10CT020', 'Sochi2.GT.AM.20MKA10CT030', 'Sochi2.GT.AM.20MKA10CT035' ]

POWER_ID: 'Sochi2.GT.AM.20CFA10CE001'
POWER_LIMIT: 20
KKS: '/home/art/InControl/data/SOCHI/kks.csv' #Файл с группами
NUM_GROUPS: 1 #Количество групп
LAG: 1 #Значение лага обучения
DIR_EXP: 'SOCHI' # Название директории в котрый сохраняются отчеты и веса(все хранится в корневой папке Reports)

#Параметры train
# TRAIN_FILE: '/home/art/InControl/' #Путь к файлу с трейн данными
# TRAIN_FILE: '/home/art/InControl/data/YUGRES/YUGRES_all.sqlite' #Путь к файлу с трейн данными
EPOCHS: 500 
BATCH_SIZE: 1024

#Параметры test
TEST_FILE: '/home/art/InControl/data/SOCHI/slices_GT.csv'
# '/home/art/InControl/data/YUGRES/YUGRES_all.sqlite'

# Параметры очистки 
TRAIN_FILE_SQL: '/home/art/InControl/data/SOCHI/slices_GT_norm.csv'
INTERVAL_REQ: [[20,30],[30,40]]
INTERVAL_CLEAR_LEN: 10000
INTERVAL_ANOMALY_LEN: 10
DISCOUNT_BETWEEN_IDX: 15

