
MEAN_NAN: False # Строки со значением Nan заменяются стредними значениями столбца
DROP_NAN: True # Строки со значением Nan удаляются


ROLLING_MEAN: False
EXP_SMOOTH: False
DOUBLE_EXP_SMOOTH: False
ROLLING_MEAN_WINDOW: 32

ROLLING_MEAN_LOSS: 128
COUNT_ANOMALY: 300
ANOMALY_TRESHOLD: 0.96
COUNT_TOP: 3

AUTO_DROP_LIST: False
DROP_LIST: [] #удаление датчиков из отчета CSV
PLOT_FEATURES: ['Sochi2.GT.AM.20MKA10CT005G','Sochi2.GT.AM.20MKA10CT010G', 'Sochi2.GT.AM.20MKA10CT020', 'Sochi2.GT.AM.20MKA10CT030', 'Sochi2.GT.AM.20MKA10CT035' ]

POWER_ID: 'Sochi2.GT.AM.20CFA10CE001-AM.Q'
POWER_LIMIT: 19
KKS: '/home/art/InControl/Offline_LSTM/SOCHI/kks_with_groups.csv' #Файл с группами
NUM_GROUPS: 12 #Количество групп
LAG: 1 #Значение лага обучения
DIR_EXP: 'SOCHI_new_19' # Название директории в котрый сохраняются отчеты и веса(все хранится в корневой папке Reports)

#Параметры train
# TRAIN_FILE: '/home/art/InControl/' #Путь к файлу с трейн данными
# TRAIN_FILE: '/home/art/InControl/data/YUGRES/YUGRES_all.sqlite' #Путь к файлу с трейн данными
EPOCHS: 500 
BATCH_SIZE: 1024

#Параметры test
TEST_FILE: '/home/art/InControl/data/SOCHI_NEW/slices.csv'
# '/home/art/InControl/data/YUGRES/YUGRES_all.sqlite'

# Параметры очистки 
TRAIN_FILE_SQL: '/home/art/Downloads/slices(3).csv'
INTERVAL_REQ: [[20,30],[30,40]]
INTERVAL_CLEAR_LEN: 10000
INTERVAL_ANOMALY_LEN: 10
DISCOUNT_BETWEEN_IDX: 15

