
MEAN_NAN: False # Строки со значением Nan заменяются стредними значениями столбца
DROP_NAN: True # Строки со значением Nan удаляются


ROLLING_MEAN: False
EXP_SMOOTH: False
DOUBLE_EXP_SMOOTH: False
ROLLING_MEAN_WINDOW: 32

AUTO_DROP_LIST: False
DROP_LIST: [] #удаление датчиков из отчета CSV
POWER_ID: 'Sochi2.GT.AM.20CFA10CE001-AM.Q'
POWER_LIMIT: 19
KKS: '/home/art/InControl/testsuite/data/sochi/kks_with_groups_Sochi_last.csv' #Файл с группами
NUM_GROUPS: 12 #Количество групп
LAG: 1 #Значение лага обучения
DIR_EXP: 'SOCHI' # Название директории в котрый сохраняются отчеты и веса(все хранится в корневой папке Reports)


EPOCHS: 1
BATCH_SIZE: 1024

#Параметры test
TEST_FILE: '/home/art/InControl/testsuite/data/sochi/slices.csv'
# '/home/art/InControl/data/YUGRES/YUGRES_all.sqlite'

# Параметры очистки 
USE_ALL_DATA: True
TRAIN_FILE_SQL: '/home/art/InControl/testsuite/data/sochi/slices.csv'
INTERVAL_REQ: [[20,30],[30,40]]
INTERVAL_CLEAR_LEN: 5000
INTERVAL_ANOMALY_LEN: 10
DISCOUNT_BETWEEN_IDX: 15

